name: Suzie Puetz
favicon: null
layout_spectrum: 0.42702
typography_spectrum: 0.81952
title: Suzie Puetz Photography
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#dddcda'
    - '#0e0d09'
    - '#a4a9ad'
    - '#433728'
    - '#6d7514'
  brandStrength: 0.875
  lightness: 0.5625
  saturation: 0.875
  rhythmicContrast: 0.25
purpose: []
